{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"assert 0 == 1\n +  where 0 = len(<ixnetwork_restpy.testplatform.sessions.ixnetwork.availablehardware.chassis.chassis.Chassis object at 0x7f4d069cf840>)","children":[{"name":"test_counter_ip_dscp","uid":"2aabc84009e6e4c5","parentUid":"c0a0faa84ff2d8adb55b68a548abd205","status":"failed","time":{"start":1741682454375,"stop":1741682478710,"duration":24335},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"c0a0faa84ff2d8adb55b68a548abd205"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 442, in set_control_state\n    self.ngpf.set_protocol_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/device/ngpf.py\", line 256, in set_protocol_state\n    self.api._ixnetwork.StartAllProtocols(\"sync\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  System Exception Caught. Exception Text: There is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\n\nSystem Exception Caught. Exception Text: There is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.","children":[{"name":"test_mka_stats","uid":"ff0164f6a2cb35b","parentUid":"3246d97c39e452fb2ea99a914b52fe9f","status":"failed","time":{"start":1741682454375,"stop":1741682511907,"duration":57532},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_encrypt","uid":"339c0e647eaeb771","parentUid":"3246d97c39e452fb2ea99a914b52fe9f","status":"failed","time":{"start":1741682454375,"stop":1741682498865,"duration":44490},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3246d97c39e452fb2ea99a914b52fe9f"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 442, in set_control_state\n    self.ngpf.set_protocol_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/device/ngpf.py\", line 256, in set_protocol_state\n    self.api._ixnetwork.StartAllProtocols(\"sync\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  System Exception Caught. Exception Text: There is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\n\nSystem Exception Caught. Exception Text: There is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.\nThere is no license available for IxN-SMACsec. Please check license availability in Ixia License Utility.\nPlease install \"930-2135: IXIA IxNetwork, Optional Software, Static MACSec Emulation\" to enable the feature.","children":[{"name":"test_encrypt_with_mka","uid":"ac7d5b38ff178577","parentUid":"3f4de06a033d7552c2f3bea99fdd162b","status":"failed","time":{"start":1741682454375,"stop":1741682504174,"duration":49799},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3f4de06a033d7552c2f3bea99fdd162b"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 450, in set_control_state\n    self.traffic_item.transmit(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 1307, in transmit\n    self._api._traffic.Apply()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/traffic/traffic.py\", line 1395, in Apply\n    return self._execute(\"apply\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Error in L2/L3 Traffic Apply","children":[{"name":"test_vxlan_b2b","uid":"18d6fce2ecacd0ad","parentUid":"ef6804d4159127be406a6111d9b6a662","status":"failed","time":{"start":1741682454375,"stop":1741682606280,"duration":151905},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"ef6804d4159127be406a6111d9b6a662"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}