{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"Exception: Time out occurred while waiting for stats to be as expected","children":[{"name":"test_encrypt_with_mka_multiple_devices","uid":"3217d929f7ec2ff4","parentUid":"3596725c47ed555d65da3fbf3423e1cd","status":"failed","time":{"start":1746414762134,"stop":1746414881854,"duration":119720},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_list_tcp_ports_e2e","uid":"2b9847a1b9cabda3","parentUid":"3596725c47ed555d65da3fbf3423e1cd","status":"failed","time":{"start":1746414762134,"stop":1746414881314,"duration":119180},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_list_tcp_ports_e2e","uid":"6d14614d3e9c4130","parentUid":"3596725c47ed555d65da3fbf3423e1cd","status":"failed","time":{"start":1746414762134,"stop":1746414885432,"duration":123298},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_latency_metrics","uid":"1e0caf256d1bf8f0","parentUid":"3596725c47ed555d65da3fbf3423e1cd","status":"failed","time":{"start":1746414762134,"stop":1746414856327,"duration":94193},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3596725c47ed555d65da3fbf3423e1cd"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 433, in set_control_state\n    self.capture.set_capture_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/capture.py\", line 495, in set_capture_state\n    self._start_capture()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/capture.py\", line 524, in _start_capture\n    self._api._ixnetwork.StartCapture()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2884, in StartCapture\n    return self._execute(\"startCapture\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  The capture can't be started on a virtual port.","children":[{"name":"test_traffic_custom_header","uid":"338a7d4239988d45","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414780936,"duration":18802},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_udp_header_with_fixed_length_checksum_e2e","uid":"1f767e74757fa163","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414777168,"duration":15034},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_traffic_ethernet_pause","uid":"34b800ad35878303","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414778390,"duration":16256},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_traffic_transmit_state","uid":"b39d990f6266b3dd","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414776869,"duration":14735},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_traffic_gptv_config","uid":"b393778514b1896e","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414779661,"duration":17527},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_udp_header_with_list_e2e","uid":"1a77a2c06e0fa8be","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414836968,"duration":74834},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_udp_header_with_counter_e2e","uid":"be7ce49b9bf38a47","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1746414762134,"stop":1746414838713,"duration":76579},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"925eb53b702459181baa2d0323af853d"},{"name":"Exception: Time out occurred while waiting for stats to be accumulated","children":[{"name":"test_stats_filter","uid":"127c89d5793381ae","parentUid":"5a7c9ad8292efb3b06ec20e1edee3646","status":"failed","time":{"start":1746414762134,"stop":1746414912564,"duration":150430},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5a7c9ad8292efb3b06ec20e1edee3646"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 276, in set_config\n    self.config_ixnetwork(config)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 374, in config_ixnetwork\n    self._ixnetwork.StartAllProtocols()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.\nSystem Exception Caught. Exception Text: Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_traffic","uid":"7f6bb547b16ed357","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1746414762134,"stop":1746414781667,"duration":19533},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_device_lag_name","uid":"584333302e0fc653","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1746414762134,"stop":1746414835410,"duration":73276},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_flow_tracking_stats","uid":"afdf338aebce58a4","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1746414762134,"stop":1746414794974,"duration":32840},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_ping","uid":"6f5e72d2063f6d2c","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1746414762134,"stop":1746414779898,"duration":17764},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_lacp_lag","uid":"c4532e2ac6ed04cb","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1746414762134,"stop":1746414809857,"duration":47723},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"b13feb8405b4b7613e3792c68aaf5e52"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException: IxNet - Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_vxlan_b2b_v6","uid":"9204cbcf6e295b74","parentUid":"da9649f3b36a8ed1237d626e3b1f8f77","status":"failed","time":{"start":1746414762134,"stop":1746414773933,"duration":11799},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_manual_gateway_mac","uid":"ca3cc3f27cfb7348","parentUid":"da9649f3b36a8ed1237d626e3b1f8f77","status":"failed","time":{"start":1746414762134,"stop":1746414826543,"duration":64409},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_compact","uid":"28fe7a5150deb97","parentUid":"da9649f3b36a8ed1237d626e3b1f8f77","status":"failed","time":{"start":1746414762134,"stop":1746414796931,"duration":34797},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"da9649f3b36a8ed1237d626e3b1f8f77"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 276, in set_config\n    self.config_ixnetwork(config)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 374, in config_ixnetwork\n    self._ixnetwork.StartAllProtocols()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_connection_portname","uid":"80f986685d66c215","parentUid":"3944caaf140ae18e2d820e4e4382219e","status":"failed","time":{"start":1746414762134,"stop":1746414769613,"duration":7479},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_ping_cvg","uid":"b24b2bf92da337f6","parentUid":"3944caaf140ae18e2d820e4e4382219e","status":"failed","time":{"start":1746414762134,"stop":1746414769561,"duration":7427},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_port_name","uid":"fab1fff17fd3da69","parentUid":"3944caaf140ae18e2d820e4e4382219e","status":"failed","time":{"start":1746414762134,"stop":1746414768132,"duration":5998},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3944caaf140ae18e2d820e4e4382219e"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException: IxNet - Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.IxNet - Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;2: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_mka_stats","uid":"f43689c811252fc2","parentUid":"967d889a6dbfba12fc32d89c58e0aeac","status":"failed","time":{"start":1746414762134,"stop":1746414852545,"duration":90411},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"967d889a6dbfba12fc32d89c58e0aeac"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 442, in set_control_state\n    self.ngpf.set_protocol_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/device/ngpf.py\", line 264, in set_protocol_state\n    self.api._ixnetwork.StartAllProtocols(\"sync\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;2: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_encrypt","uid":"4d4f7b85ce8cd229","parentUid":"5a3b982fe6282f1ba6d725421c622337","status":"failed","time":{"start":1746414762134,"stop":1746414838351,"duration":76217},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5a3b982fe6282f1ba6d725421c622337"},{"name":"assert 400 == 500","children":[{"name":"test_device_connection","uid":"da66471ca7c294ea","parentUid":"5dc59fb3fa66403244a17904c0e00b01","status":"failed","time":{"start":1746414762134,"stop":1746414821230,"duration":59096},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5dc59fb3fa66403244a17904c0e00b01"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 276, in set_config\n    self.config_ixnetwork(config)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 364, in config_ixnetwork\n    self.traffic_item.config()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 916, in config\n    ixn_traffic_item = self.get_ixn_config(self._config)[0]\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 574, in get_ixn_config\n    self._importconfig(imports)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 502, in _importconfig\n    raise SnappiIxnException(\n [{'xpath': '', 'message': 'Object reference not set to an instance of an object.', 'severity': 'kError', 'category': 'invalidCommit', 'property': 'noAtt'}, {'xpath': '', 'message': 'Object reference not set to an instance of an object.', 'severity': 'kError', 'category': 'invalidCommit', 'property': 'noAtt'}]","children":[{"name":"test_static_and_lacp_lag","uid":"bea4dde9289625e9","parentUid":"ab296ffc9c5c846ca3b870de4924a611","status":"failed","time":{"start":1746414762134,"stop":1746414812498,"duration":50364},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_phb_ecn","uid":"85adf3f834135a58","parentUid":"ab296ffc9c5c846ca3b870de4924a611","status":"failed","time":{"start":1746414762134,"stop":1746414881405,"duration":119271},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_static_lag","uid":"e45e4b7318873e63","parentUid":"ab296ffc9c5c846ca3b870de4924a611","status":"failed","time":{"start":1746414762134,"stop":1746414854594,"duration":92460},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"ab296ffc9c5c846ca3b870de4924a611"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 442, in set_control_state\n    self.ngpf.set_protocol_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/device/ngpf.py\", line 264, in set_protocol_state\n    self.api._ixnetwork.StartAllProtocols(\"sync\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.\nSystem Exception Caught. Exception Text: Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_vxlan_b2b","uid":"8a91ed965c79df67","parentUid":"3961465682e238d8bcb80c03cf6efe1b","status":"failed","time":{"start":1746414762134,"stop":1746414824837,"duration":62703},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3961465682e238d8bcb80c03cf6efe1b"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException: IxNet - Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;2: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_encrypt_with_mka","uid":"ff60426a0596b77b","parentUid":"47595611af44296a1f58f1ac5c4b6caf","status":"failed","time":{"start":1746414762134,"stop":1746414875329,"duration":113195},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_bgpv6_routes","uid":"b858348f299519c0","parentUid":"47595611af44296a1f58f1ac5c4b6caf","status":"failed","time":{"start":1746414762134,"stop":1746414838093,"duration":75959},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"47595611af44296a1f58f1ac5c4b6caf"},{"name":"assert 0 == 1\n +  where 0 = len(<ixnetwork_restpy.testplatform.sessions.ixnetwork.availablehardware.chassis.chassis.Chassis object at 0x7f99c6376ac0>)","children":[{"name":"test_counter_ip_dscp","uid":"e23859ea5460b77d","parentUid":"aef9472917e79cd9053b25ed950266e4","status":"failed","time":{"start":1746414762134,"stop":1746414787351,"duration":25217},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"aef9472917e79cd9053b25ed950266e4"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}